import { MyText, SafeView } from "@elements/SharedElements";
import type { NextPage } from "next";
import Head from "next/head";
import Page from "../app/components/Page";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Project</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Page />

			<SafeView>
				<footer className="flex flex-col justify-center py-8 px-0 items-center">
					<a
						href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						target="_blank"
						rel="noopener noreferrer"
					>
						<MyText>Powered by Our Company</MyText>
					</a>
				</footer>
			</SafeView>
		</>
	);
};

export default Home;
